/*
 * Anton dela Cruz
 * MakingPurchases.java
 * This GUI calulates tax, subtotal, and grand total, depending on the order of user.
 * October 9, 2018
 */

/**
 *
 * @author andel7651
 */
public class MakingPurchaces extends javax.swing.JFrame {

    /**
     * Creates new form MakingPurchaces
     */
    public MakingPurchaces() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storename = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        amt1 = new javax.swing.JTextField();
        amt2 = new javax.swing.JTextField();
        amt3 = new javax.swing.JTextField();
        amt4 = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        lblsub = new javax.swing.JLabel();
        lblgrand = new javax.swing.JLabel();
        amtsub = new javax.swing.JLabel();
        amtgrand = new javax.swing.JLabel();
        lbltax = new javax.swing.JLabel();
        amttax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        storename.setFont(new java.awt.Font("Rafika", 2, 24)); // NOI18N
        storename.setForeground(new java.awt.Color(0, 102, 0));
        storename.setText("Queen's Archery Shop");

        item1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        item1.setText("Carbon Fiber Longbow ($149.99)");

        item2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        item2.setText("Recurve Bow ($199.99)");

        item3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        item3.setText("Oneida Kestral Compound Bow ($399.99)");

        item4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        item4.setText("Cross-Cable Compound Bow ($419.99)");

        amt1.setText("0");
        amt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amt1ActionPerformed(evt);
            }
        });

        amt2.setText("0");

        amt3.setText("0");

        amt4.setText("0");

        button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        button.setText("Calculate Cost");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        lblsub.setText("Subtotal:");

        lblgrand.setText("Grand Total:");

        amtsub.setText("$0.00");

        amtgrand.setText("$0.00");

        lbltax.setText("Taxes (13%):");

        amttax.setText("$0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item4)
                            .addComponent(item1)
                            .addComponent(item2)
                            .addComponent(item3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amt2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amt1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amt4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amt3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblgrand)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amtgrand))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblsub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amtsub))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbltax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(amttax))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button)
                                .addGap(10, 10, 10))))
                    .addComponent(storename, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(storename)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1)
                    .addComponent(amt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item2)
                    .addComponent(amt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltax)
                    .addComponent(amttax))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item3)
                    .addComponent(amt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsub)
                    .addComponent(amtsub))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item4)
                    .addComponent(amt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgrand)
                    .addComponent(amtgrand))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        
        
           
    }
    private void amt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amt1ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        
        double num1 = 149.99 * Double.parseDouble(amt1.getText());
        double num2 = 199.99 * Double.parseDouble(amt2.getText());
        double num3 = 399.99 * Double.parseDouble(amt3.getText());
        double num4 = 419.99 * Double.parseDouble(amt4.getText());
        
        double tax, sub, grand;
        
        tax = ((num1 + num2 + num3 + num4) * 0.13);
        sub = num1 + num2 + num3 + num4;
        grand = (num1 + num2 + num3 + num4) * 1.13;
         
        tax = Math.round(tax * 100) / 100;
        
        sub = Math.round(sub * 100) / 100;
        
        grand = Math.round(grand * 100) / 100;
        
        amtsub.setText("$" + sub);
        amttax.setText("$" + tax);
        amtgrand.setText("$" + grand);   
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingPurchaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingPurchaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingPurchaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPurchaces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingPurchaces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt1;
    private javax.swing.JTextField amt2;
    private javax.swing.JTextField amt3;
    private javax.swing.JTextField amt4;
    private javax.swing.JLabel amtgrand;
    private javax.swing.JLabel amtsub;
    private javax.swing.JLabel amttax;
    private javax.swing.JButton button;
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel item4;
    private javax.swing.JLabel lblgrand;
    private javax.swing.JLabel lblsub;
    private javax.swing.JLabel lbltax;
    private javax.swing.JLabel storename;
    // End of variables declaration//GEN-END:variables
}
